# https://help.github.com/articles/using-jekyll-with-pages/
# Github Pages override these options.
safe: true
lsi: false

# Dependencies
markdown:     kramdown
highlighter:  rouge

# Permalinks
#
permalink:           pretty

# Setup
title:               /* the devil is in the detail */
tagline:             Minjang Kim's blog (김민장의 블로그)
description:         김민장의 블로그 | Minjang Kim's Blog
url:                 http://minjang.github.io
baseurl:             ''
paginate:            1
disqus_shortname:    minjangkim
disqus_url:          http://minjang.github.io

# About/contact
author:
  name:              Minjang Kim
  url:               https://twitter.com/minjangk
  email:             minjang.kim@gmail.com

github:
  repo:              'https://github.com/minjang/minjang.github.io'

version:             1.0.0

pages_list:
  About: ['소개', '/about']
  Archive: ['글목록', '/archive']
  Feed: ['구독', '/feed.xml']

gems:
  - jekyll-gist
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
